# Generated by Django 5.2.8 on 2025-11-30 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('image_file', models.BinaryField()),
                ('image_format', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('calendar_data', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_errors', models.JSONField(blank=True, default=list)),
                ('source_image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_calendar', to='academic_calendars.academiccalendarimage')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
