# Generated by Django 5.2.8 on 2025-12-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('letivo', 'Dia Letivo'), ('nao_letivo', 'Dia Não Letivo'), ('feriado_nacional', 'Feriado Nacional'), ('feriado_municipal', 'Feriado Municipal'), ('ponto_facultativo', 'Ponto Facultativo'), ('ferias', 'Férias'), ('recesso', 'Recesso'), ('planejamento', 'Planejamento'), ('avaliacao_recuperacao', 'Avaliação de Recuperação'), ('evento', 'Evento')], max_length=50, unique=True, verbose_name='Tipo')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('color_hex', models.CharField(blank=True, help_text='Código hexadecimal da cor (ex: #FF0000)', max_length=7, null=True, verbose_name='Cor Hexadecimal')),
            ],
            options={
                'verbose_name': 'Legenda',
                'verbose_name_plural': 'Legendas',
                'ordering': ['type'],
            },
        ),
    ]
