# Generated by Django 5.2.8 on 2025-12-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendars', '0002_legend'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('type', models.CharField(choices=[('letivo', 'Dia Letivo'), ('nao_letivo', 'Dia Não Letivo'), ('feriado_nacional', 'Feriado Nacional'), ('feriado_municipal', 'Feriado Municipal'), ('ponto_facultativo', 'Ponto Facultativo'), ('ferias', 'Férias'), ('recesso', 'Recesso'), ('planejamento', 'Planejamento'), ('avaliacao_recuperacao', 'Avaliação de Recuperação'), ('evento', 'Evento')], max_length=50, verbose_name='Tipo')),
                ('labels', models.JSONField(blank=True, default=list, help_text='Lista de rótulos adicionais para o dia', verbose_name='Rótulos')),
                ('year', models.IntegerField(help_text='Ano do calendário letivo', verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Dia do Calendário',
                'verbose_name_plural': 'Dias do Calendário',
                'ordering': ['date'],
                'unique_together': {('date', 'year')},
            },
        ),
    ]
