# Generated by Django 5.2.8 on 2025-12-09 03:12

from django.db import migrations, models
from django.db.models import Count


def deduplicate_calendars(apps, schema_editor):
    AcademicCalendar = apps.get_model('academic_calendars', 'AcademicCalendar')
    duplicates = (
        AcademicCalendar.objects.values('year')
        .annotate(c=Count('id'))
        .filter(c__gt=1)
    )
    for entry in duplicates:
        year = entry['year']
        qs = AcademicCalendar.objects.filter(
            year=year).order_by('-processed_at', '-id')
        keep = qs.first()
        qs.exclude(id=keep.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendars', '0003_calendarday'),
    ]

    operations = [
        migrations.RunPython(deduplicate_calendars,
                             reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='academiccalendar',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
