# Generated by Django 5.2.8 on 2025-11-21 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('password', models.CharField()),
                ('reduction_day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')])),
                ('diary_type', models.CharField(choices=[('c1', 'C1'), ('c2', 'C2')])),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.school')),
            ],
        ),
    ]
