# Generated by Django 5.2.8 on 2025-11-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_school_delete_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['code', 'school__name']},
        ),
    ]
