# Generated by Django 5.2.8 on 2025-12-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_class_teacher'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(related_name='teachers', to='classes.class'),
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
    ]
