# Generated by Django 5.2.8 on 2025-11-30 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_calendar', '0001_initial'),
        ('classes', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_registry', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('progress', models.IntegerField(default=0, help_text='Progresso da caderneta (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='classes.class')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='academic_calendar.academiccalendar')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebooks', to='teacher.teacher')),
            ],
            options={
                'ordering': ['status', 'teacher__code'],
            },
        ),
    ]
